spring:
  security.oauth2.client:
    registration:
      google:
        client-id: 1053nhhjhjbmbjb
        client-secret: mdfjhqeudjqwenfdebjhjecknm
      github:
        client-id: ueuhknvdjgwdb
        client-secret: hfgknjbvyhj


